### ISSUE TITLE
docker compose in function app fails to load

### ISSUE THREAD

**Issue by justinh-kairos** [Azure/azure-functions-docker#836]
Trying to start a function app with docker compose - I have two separate services in my compose config, which both start up fine as individual containers. When I try to start them both with the compose option, I get the following error in my error logs:

```
2023-01-19T23:16:22.793Z INFO - Pulling image: mcr.microsoft.com/azure-functions/compose:4-composedmvyc2lvbjogijmu-appservice-stage2
2023-01-19T23:16:22.983Z ERROR - DockerApiException: Docker API responded with status code=NotFound, response={"message":"manifest for mcr.microsoft.com/azure-functions/compose:4-composedmvyc2lvbjogijmu-appservice-stage2 not found: manifest unknown: manifest tagged by \"4-composedmvyc2lvbjogijmu-appservice-stage2\" is not found"}
```

**Comment by CooperLink** [comment]
The manifest file appears to be incorrect. We do not provide any images under the /compose: nomenclature.  Replace that information the name of the specific image you are attempting to use. For example, mcr.microsoft.com/azure-functions/node:4-node14-appservice-stage3

**Comment by justinh-kairos** [comment]
This is not the image I'm referencing in my compose file. For reference, here is the compose config:
```
version: "3.9"
name: titan-pinata
services:
  azure-functions:
    container_name: azure-functions
    image: tjwilderkairos/azure-functions:latest
    restart: always
    environment:
      # Parameters removed for posting to Github
    ports:
      - "80:80"
  titan:
    container_name: titan-flask
    image: tjwilderkairos/titan-flask:latest
    restart: always
    environment:
      # Parameters removed for posting to Github
    ports:
      - "8080:8080"
```

I'd also appreciate if you didn't close the issue before I've accepted a resolution - it comes across as flippant.
