### ISSUE TITLE
Using with Docker Compose

### ISSUE THREAD

**Issue by alizahid** [Azure/azure-functions-docker#84]
Here's my `docker-compose.yml`;

```
version: '3'

services:
  func:
    environment:
      AzureWebJobsScriptRoot: /www/src
      AzureFunctionsJobHost__Logging__Console__IsEnabled: 'true'
    image: mcr.microsoft.com/azure-functions/node
    ports:
      - 7071:80
    restart: always
    volumes:
      - .:/www
    working_dir: /www

  mongo:
    image: mongo:3.4
    restart: always
```

Three questions;
1. Is the behavior around `AzureFunctionsJobHost__Logging__Console__IsEnabled` sorted yet? Is there a cleaner flag I can set to enable verbose'ish logging?
2. When I `docker-compose up`, my app cannot access the environment variables in `local.settings.json`. How can I get it to load variables from there?
3. This app always boots in production mode; `Hosting environment: Production`. How can I get to run in development mode so `NODE_ENV` is set to `development` and there's more logging, etc. Couldn't find any documentation on this.

cc @mhoeger @paulbatum
